export const catsData = [
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScWeiayDAjzX2MnpJLbSBqx5MQwSDcpkTyxg&s",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody", "insomniac"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQY7AdQXmu2p-hACCwEgxmll9owEiGePDYZXg&s",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-KRYYsyY-PGenb9-8alP6nxcU17Oug0OqMg&s",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["confused", "sad"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8uHl1DBdR818p7XrAjtkM3grYxahBNWFOtA&s",
        alt: "A cat looking confused",
    },
    {
        emotionTags: ["dominant", "moody"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA6XfRXZpgLZFvhmgR8wSd-LiDA-K3O1zroA&s",
        alt: "A cat looking dominant",
    },
    {
        emotionTags: ["happy", "relaxed"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuwFIg1OkUx4_aWVsdKuwB1fmLd0V0lJ469A&s",
        alt: "A cat looking happy",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw_nuWJDTWucQH9WQjOe5AyHtyMJZZtRFGhw&s",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw_nuWJDTWucQH9WQjOe5AyHtyMJZZtRFGhw&s",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRved2wGveigt6Doww7SiWIKvbhNX4BtE15mA&s",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRved2wGveigt6Doww7SiWIKvbhNX4BtE15mA&s",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["relaxed"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8zE3eqAH2TV7SXksBCRa-NiiGG7CapiBJcw&s",
        alt: "A cat looking lazy",
    },
    {
        emotionTags: ["scared"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwbPFJt3kB5rYlk9afVkKm86Pod5Q4geMhKA&s",
        alt: "A cat looking nervous",
    },
    {
        emotionTags: ["sad"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8uHl1DBdR818p7XrAjtkM3grYxahBNWFOtA&s",
        alt: "A cat looking sad",
    },
    {
        emotionTags: ["sad", "moody"],
        isGif: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7wKqIuhc4nQ3Tcn2BuovVn68zmvOkjwnpyA&s",
        alt: "A cat looking sad",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScWeiayDAjzX2MnpJLbSBqx5MQwSDcpkTyxg&s",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScWeiayDAjzX2MnpJLbSBqx5MQwSDcpkTyxg&s",
        alt: "A cat looking angry",
    },
    {
        emotionTags: ["confused"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8uHl1DBdR818p7XrAjtkM3grYxahBNWFOtA&s",
        alt: "A cat looking confused",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA6XfRXZpgLZFvhmgR8wSd-LiDA-K3O1zroA&s",
        alt: "A cat looking dominant",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuwFIg1OkUx4_aWVsdKuwB1fmLd0V0lJ469A&s",
        alt: "A cat looking happy",
    },
    {
        emotionTags: ["hungry", "sad", "confused"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw_nuWJDTWucQH9WQjOe5AyHtyMJZZtRFGhw&s",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw_nuWJDTWucQH9WQjOe5AyHtyMJZZtRFGhw&s",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw_nuWJDTWucQH9WQjOe5AyHtyMJZZtRFGhw&s",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["insomniac", "scared"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRved2wGveigt6Doww7SiWIKvbhNX4BtE15mA&s",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8zE3eqAH2TV7SXksBCRa-NiiGG7CapiBJcw&s",
        alt: "A cat looking relaxed",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8zE3eqAH2TV7SXksBCRa-NiiGG7CapiBJcw&s",
        alt: "A cat looking relaxed",
    },
    {
        emotionTags: ["scared", "sad"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwbPFJt3kB5rYlk9afVkKm86Pod5Q4geMhKA&s",
        alt: "A cat looking nervous",
    },
    {
        emotionTags: ["scared"],
        isGif: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwbPFJt3kB5rYlk9afVkKm86Pod5Q4geMhKA&s",
        alt: "A cat looking scared",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7wKqIuhc4nQ3Tcn2BuovVn68zmvOkjwnpyA&s",
        alt: "A cat looking sad",
    },
]
